import { ProductsInterface } from "@/types/product.interface";

export const productsData: ProductsInterface[] = [
    {
        id: 1,
        name: '大鶴望蘭',
        description: '一種受歡迎的室內蘭花。它擁有優雅的花朵和長而綠色的葉子，是一種美麗而容易栽培的植物。',
        imagePath: '',
        price: 100,
        available: 10,
        monthlyNews: false,
    },
    {
        id: 2,
        name: '天堂鳥',
        description: '一種迷人而獨特的熱帶花卉。它以其鮮豔多彩的花朵而聞名，擁有豔紅、橙色、黃色等鮮豔的色彩，彷彿一片燃燒著的火焰。',
        imagePath: '',
        price: 100,
        available: 10,
        monthlyNews: false,
    },
    {
        id: 3,
        name: '仙人掌',
        description: '一類特殊的多肉植物，以其獨特的外觀和適應乾燥環境的能力而聞名。它們具有肉質的葉子和莖幹，能夠儲存水分以應對缺水的情況。',
        imagePath: '',
        price: 100,
        available: 10,
        monthlyNews: false,
    },
    {
        id: 4,
        name: '白鶴芋',
        description: '一種受歡迎的觀葉植物，具有獨特的葉子和迷人的外觀。它的學名是Alocasia zebrina，常被稱為斑馬葉鶴芋，因為其葉片上有黑色和白色的條紋，猶如斑馬皮紋一般。',
        imagePath: '',
        price: 100,
        available: 10,
        monthlyNews: false,
    },
    {
        id: 5,
        name: '印度榕',
        description: '印度榕擁有獨特的外觀和生長習性。它的葉子呈橢圓形或卵形，深綠色且有光澤。葉片之間形成的密集綠色簇擁是印度榕的特色之一。',
        imagePath: '',
        price: 100,
        available: 10,
        monthlyNews: false,
    },
    {
        id: 6,
        name: '蘆薈',
        description: '蘆薈具有肉質的葉子和獨特的外觀。它的葉子呈長條形，厚實且帶有齒狀的邊緣。葉子通常呈淺綠色，但也有品種呈現深綠色或帶有斑點。',
        imagePath: '',
        price: 100,
        available: 10,
        monthlyNews: false,
    },
    {
        id: 7,
        name: '虎尾蘭',
        description: '一種受歡迎的室內蘭花，也被稱為蝴蝶蘭。它原產於東南亞地區，現在已廣泛種植和銷售。',
        imagePath: '',
        price: 100,
        available: 10,
        monthlyNews: false,
    },
    {
        id: 8,
        name: '美鐵芋亞',
        description: '一種迷人的多年生植物，也被稱為斑葉象耳。它原產於亞洲熱帶地區，現在被廣泛種植作為觀賞植物。',
        imagePath: '',
        price: 100,
        available: 10,
        monthlyNews: false,
    },
    {
        id: 9,
        name: '香龍血樹',
        description: '香龍血樹以其漂亮的綠葉和獨特的樹形而受到人們的喜愛。它的葉片呈狹長形，深綠色，有著明顯的縱向葉脈，使其顯得格外優雅。',
        imagePath: '',
        price: 100,
        available: 10,
        monthlyNews: false,
    },
    {
        id: 10,
        name: '假葉樹',
        description: '假葉樹的樹幹通常由金屬或塑料製成，外表經過精心的塗裝處理，使其看起來像真實的樹幹。葉子則由絲綢、塑料或其他合成材料製成，並通過精確的模擬葉脈和葉形來呈現植物的真實外觀。',
        imagePath: '',
        price: 100,
        available: 10,
        monthlyNews: false,
    },
    {
        id: 11,
        name: '棕竹',
        description: '棕竹的莖幹通常是筆直且細長的，呈現淡黃色至淡綠色的外觀。它的葉子是長而狹窄的，呈綠色且具有竹葉的典型縱條紋路。這種植物的葉子較為硬挺，結構堅實，非常耐久。',
        imagePath: '',
        price: 100,
        available: 10,
        monthlyNews: false,
    },
    {
        id: 12,
        name: '琴葉榕',
        description: '琴葉榕的葉子呈現心形或琴琶形狀，並具有明顯的葉脈紋路。葉子呈深綠色，表面光滑而有光澤。',
        imagePath: '',
        price: 100,
        available: 10,
        monthlyNews: false,
    },
    {
        id: 13,
        name: '黃金虎尾蘭',
        description: '黃金虎尾蘭的葉子呈長而尖的形狀，呈現出明亮的金黃色或橙黃色，有時帶有斑點或斑紋。這種植物的葉子生長緊密，形成緊湊而豐滿的觀葉植株。',
        imagePath: '',
        price: 100,
        available: 10,
        monthlyNews: false,
    },
    {
        id: 14,
        name: '黃金葛',
        description: '黃金葛的葉子呈心形，具有亮麗的金黃色或黃綠色，並帶有顯著的紋路和細緻的質地。它的葉子密集生長在長而彎曲的藤蔓上，形成一個綠意盎然的覆蓋物。',
        imagePath: '',
        price: 100,
        available: 10,
        monthlyNews: false,
    },
    {
        id: 15,
        name: '圓葉刺軸櫚',
        description: '圓葉刺軸櫚的葉子呈圓形或略呈橢圓形，具有深綠色的質地，並且葉緣帶有尖刺。它的葉子生長在直立的莖上，形成一個緊湊而豐滿的觀葉植株。',
        imagePath: '',
        price: 100,
        available: 10,
        monthlyNews: false,
    },
    {
        id: 16,
        name: '葉門鐵樹',
        description: '葉門鐵樹的特點是其獨特的葉子形狀和濃密的枝葉結構。它的葉子呈橢圓形或長橢圓形，有時帶有鋸齒狀的邊緣，並以深綠色或紅褐色為主。',
        imagePath: '',
        price: 100,
        available: 10,
        monthlyNews: false,
    },
    {
        id: 17,
        name: '綠帝王蔓綠絨',
        description: '綠帝王蔓綠絨以其獨特的綠色絨毛狀葉子而聞名。它的葉子厚實且柔軟，觸感像絨布一樣，呈現深綠色的鮮豔色彩。葉子的形狀呈心形或卵形，排列在蔓狀莖上，形成緊密的葉群。',
        imagePath: '',
        price: 100,
        available: 10,
        monthlyNews: false,
    },
    {
        id: 18,
        name: '銀后虎尾蘭',
        description: '銀后虎尾蘭以其美麗的葉子而聞名，葉子呈橢圓形，具有青綠色的底色並帶有銀白色的斑紋。這種銀白色的斑紋使得它的葉子看起來像是被銀色霜霧覆蓋，給人一種獨特而優雅的外觀。',
        imagePath: '',
        price: 100,
        available: 10,
        monthlyNews: false,
    },
    {
        id: 19,
        name: '龜背芋',
        description: '葉子呈心形或箭頭狀，具有鮮豔的綠色或深綠色，並且帶有明顯的脈紋。葉片表面光滑而亮麗，葉柄呈綠色或深紫色，增添了視覺上的吸引力。',
        imagePath: '',
        price: 100,
        available: 10,
        monthlyNews: false,
    },
    {
        id: 20,
        name: '花葉萬年青',
        description: '葉子呈現直立、長而厚實的形狀，通常帶有深綠色或灰綠色的條紋或斑點。花葉萬年青是一種非常耐久且易於照料的植物，適合放置在室內環境中，如辦公室、客廳或臥室。',
        imagePath: 'dieffenbachia-seguine.png',
        price: 100,
        available: 10,
        monthlyNews: true,
    },
]